name: "GitHubAppTokens Test"
on:
  push:
    branches:
      - main
    paths:
      - src/*
      - test/*
      - Project.toml
      - .github/workflows/test.yaml
  pull_request:
    paths:
      - src/*
      - test/*
      - Project.toml
      - .github/workflows/test.yaml
  workflow_call:
    secrets:
      TEST_GHAPP_PRIVKEY:
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.7'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        include:
          - version: '1.7.2'
            os: 'ubuntu-latest'
          - version: '1.1.1'
            os: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - name: "Test"
        run: julia --color=yes --project=. -e 'using Pkg; Pkg.test("GitHubAppTokens")'
        shell: bash
        env:
          APP_ID: ${{ vars.TEST_GHAPP_ID }}
          APP_PRIVKEY: ${{ secrets.TEST_GHAPP_PRIVKEY }}
